### ISSUE TITLE
Installation of fastqc - Mac OSX - for command line

### ISSUE THREAD

**Issue by ramongallego** [s-andrews/FastQC#13]
Hi there,

I am trying to install fastqc in macOS High Sierra. The GUI version works perfectly after I installed the Java JRE. But I can't install the command-line version of it successfully. 
This is what I have tried:
1) Download and expand FastQC-0.11.7.tar.gz
2) Navigate to the expanded folder
3) run `chmod` +x fastqc`
4) `sudo ln -s /Absolute/path/to/fastqc /usr/local/bin/fastqc`

If I check the installation by running `which fastqc`, it finds it ok in 
`usr/local/bin/fastqc`
But when I try to run it 
`fastqc --help`

the output is
`This is the source distribution of FastQC.  You need to get the compiled version if you want to run the program`

Any ideas on what I am missing?

**Comment by s-andrews** [comment]
You've downloaded the wrong zip file from the project page. For command line use on OSX you want the one labelled win/Linux.  The download you need is:

https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.7.zip

If you delete the folder you have now and replace it with the contents of that zip file then that should work.

**Comment by ramongallego** [comment]
Works perfect - Thanks

**Comment by soluna1** [comment]
Sorry, I have the same issue, I tried both version, but it didn't work from terminal mac, although it works as a normal double-click app. 

I've got this error:
MacBook-Pro:FastQC my_mac$ fastqc --version
-bash: /usr/local/bin/fastqc: cannot execute binary file

Any possible help on this?

Many thanks!!

Sol

**Comment by s-andrews** [comment]
Can you post the output of 

```
ls -l /usr/local/bin/fastqc
```

**Comment by soluna1** [comment]
This is the output:
-rwxr-xr-x@ 1 root  staff  720 21 Oct 23:22 /usr/local/bin/fastqc

I think it is solved now, it seems that I was missing the "./" before trying to run the app, 
$ ./fastqc --version
FastQC v0.11.8

thanks a lot !!

**Comment by soluna1** [comment]
Yes, that was the problem too, I've rm the fastqc file from the /local/bin and now it seems accessible from everywhere. Great!! though it took me some time. Many thanks!

**Comment by 1740903** [comment]
Hello. 
I still have problem about making fastqc available everywhere. the output of "ls -l /usr/local/bin/fastqc" for me is : /usr/local/bin/fastqc -> /Absolute/path/to/fastqc

would you help me please?
now I can only use fastqc when I am on that special folder and not everywhere

**Comment by s-andrews** [comment]
The bit which says /Absolute/path/to/fastqc isn't meant to be taken literally, but replaced with the path where you actually uncompressed the fastqc zip file, so on my machine it would be /Users/andrewss/FastQC/fastqc.  You need to change that to the location on your machine where fastqc is actually installed.

Once you've worked that out then delete the (broken) link you have at the moment and re-create it with the correct location.

**Comment by 1740903** [comment]
thank you so much. with your help I solved my problem.

**Comment by JayalalKJ** [comment]
why I get this error?

ln: failed to create symbolic link '/usr/local/bin/fastqc': File exists

**Comment by s-andrews** [comment]
There's already a file at /usr/local/bin/fastqc and ```ln``` won't overwrite it by default.

You can run:

```
ls -l /usr/local/bin/fastqc
```

..to see what the existing file is.  It's probably just a link to a previous installation.  If you're happy to overwrite it then you can run:

```
sudo ln -sf /path/to/FastQC/fastqc /usr/local/bin/fastqc 
```

..also, just to be clear ```/path/to/FastQC``` shouldn't be written literally, but replaced with the path under which you actually unzipped the fastqc distribution.

**Comment by wajm** [comment]
Hi there,

I am trying to install fastqc 0.11.9 in Mac OS Catailina.
The download I did from https://github.com/s-andrews/FastQC/archive/v0.11.9.zip (I think this is compiled version, right?)
Then unzip the file and test fastqc.
the output is
This is the source distribution of FastQC. You need to get the compiled version if you want to run the program.
Compiled version is not necessary to do chmod, isn't it?
Any ideas on what I am missing?

**Comment by s-andrews** [comment]
You are downloading the source code.  The correct download for the OSX compiled version would be:

http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.9.dmg

**Comment by wajm** [comment]
I think this link is GUI version, I want to command line version.
Thank you.

**Comment by s-andrews** [comment]
Then you'd use the win/linux version:

http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.9.zip

**Comment by MACRODER** [comment]
Hi! After searching everywhere I found this post that might help me to solve my problem. I'm trying to install the newest version of fastqc. I have downloaded **FastQC v0.11.9 (Win/Linux zip file)** from [http://www.bioinformatics.babraham.ac.uk/projects/fastqc](url). I have follow the instalation steps indicated here [https://raw.githubusercontent.com/s-andrews/FastQC/master/INSTALL.txt](url). I am using windows with linux (Ubuntu) as a subsystem. BUT, I'm only able to run fastqc when I'm on the specific folder that has the fastq file. If I am in that folder and I run `./fastqc -v`, I get `FastQC v0.11.9` as output. I can also run it interactively from run_fastqc.bat file. From the manual, I understand we need to make the wrapper script called fastqc executable using `chmod 755 fastqc` and I did that. But when I try to run `sudo ln -s /path/to/FastQC/fastqc /usr/local/bin/fastqc` I get this error: `ln: failed to access '/mnt/c/Users/MyUser/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/home/myuser/.local/bin/fastqc': Permission denied`

What am I doing wrong?
Thank you!

**Comment by zz-xiao** [comment]
> Hi! After searching everywhere I found this post that might help me to solve my problem. I'm trying to install the newest version of fastqc. I have downloaded **FastQC v0.11.9 (Win/Linux zip file)** from [http://www.bioinformatics.babraham.ac.uk/projects/fastqc](url). I have follow the instalation steps indicated here [https://raw.githubusercontent.com/s-andrews/FastQC/master/INSTALL.txt](url). I am using windows with linux (Ubuntu) as a subsystem. BUT, I'm only able to run fastqc when I'm on the specific folder that has the fastq file. If I am in that folder and I run `./fastqc -v`, I get `FastQC v0.11.9` as output. I can also run it interactively from run_fastqc.bat file. From the manual, I understand we need to make the wrapper script called fastqc executable using `chmod 755 fastqc` and I did that. But when I try to run `sudo ln -s /path/to/FastQC/fastqc /usr/local/bin/fastqc` I get this error: `ln: failed to access '/mnt/c/Users/MyUser/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/home/myuser/.local/bin/fastqc': Permission denied`
> 
> Edit: I did not mentioned it, but I have of course replaced /path/to/FastQC/fastqc and /usr/local/bin/fastqc whit the correct paths
> 
> What am I doing wrong?
> Thank you!

ah, I definitely have the same problem. 
"zsh: permission denied: fastqc"

**Comment by s-andrews** [comment]
This looks like something specific to the windows linux subsystem.  That's not an environment I've directly used.

A few things to check:

1.  Does /usr/local/bin actually exist? (what does ```ls /usr/local/bin``` give you?)

2. Does sudo work?  What does ```sudo whoami``` say?

3. Can you write to ```/usr/local/bin```?  Try ```touch /usr/local/bin/test```

4. Is there already a fastqc entry in ```/usr/local/bin```?  What do you get from ```ls -l /usr/local/bin/fastqc```

**Comment by zz-xiao** [comment]
> This looks like something specific to the windows linux subsystem. That's not an environment I've directly used.
> 
> A few things to check:
> 
> 1. Does `/usr/local/bin` actually exist? (what does `ls /usr/local/bin` give you?)
> 2. Does sudo work?  What does `sudo whoami` say?
> 3. Can you write to `/usr/local/bin`?  Try `sudo touch /usr/local/bin/test`
> 4. Is there already a fastqc entry in `/usr/local/bin`?  What do you get from `ls -l /usr/local/bin/fastqc`

1. yes, it exists. I can cd to /usr/local/bin, then display lots directories including fastqc. when I cd into the fastqc, it displays the same contents in the absolute path folder (/Downloads)
2. type `sudo whoami`, require the password, then show "root"
3. yes, can write in with "test"
4.amswer: 
 lrwxr-xr-x  1 root  admin  41 Mar 11 11:56 /usr/local/bin/fastqc -> /Users/xiaodemon/Downloads/Bioinfo/FastQC

it is the latest Mac Catalina system (10.15.3). I installed weeks ago, it worked. but today I mistakenly deleted it, then install again. it displays just like below:
zsh: permission denied: fastqc.

Thank you.

**Comment by s-andrews** [comment]
Ah - from within /usr/local/bin you shouldn't be able to see the fastqc *folder* you should be able to see the launch script.  You've made the link to the wrong place.

To fix it first delete the existing link:

```sudo rm /usr/local/bin/fastqc```

Then recreate it in the right place.

```sudo ln -s /Users/xiaodemon/Downloads/Bioinfo/FastQC/fastqc /usr/local/bin/fastqc```

Then it should work.

**Comment by zz-xiao** [comment]
> Ah - from within /usr/local/bin you shouldn't be able to see the fastqc _folder_ you should be able to see the launch script. You've made the link to the wrong place.
> 
> To fix it first delete the existing link:
> 
> `sudo rm /usr/local/bin/fastqc`
> 
> Then recreate it in the right place.
> 
> `sudo ln -s /Users/xiaodemon/Downloads/Bioinfo/FastQC/fastqc /usr/local/bin/fastqc`
> 
> Then it should work.

AH! thanks! it works! 
but I did the same when I create the link? what's wrong there? 
but maybe I forget the sudo?

**Comment by s-andrews** [comment]
That would certainly fit with the "Permission denied" error

**Comment by zz-xiao** [comment]
> That would certainly fit with the "Permission denied" error

;) thanks!

**Comment by MACRODER** [comment]
> This looks like something specific to the windows linux subsystem. That's not an environment I've directly used.
> 
> A few things to check:
> 
> 1. Does `/usr/local/bin` actually exist? (what does `ls /usr/local/bin` give you?)
> 2. Does sudo work?  What does `sudo whoami` say?
> 3. Can you write to `/usr/local/bin`?  Try `sudo touch /usr/local/bin/test`
> 4. Is there already a fastqc entry in `/usr/local/bin`?  What do you get from `ls -l /usr/local/bin/fastqc`

Hi! Thanks for the answer. I have checked what you mentioned and obtained this:
1. It gives only fastqc
2. It says root
3. Yes, I can write. Now when I do `ls /usr/local/bin` it gives fastqc and test
4. I get `lrwxrwxrwx 1 root root 68 Mar 11 12:39 /usr/local/bin/fastqc -> mnt/c/Users/MacaRW/Documents/Postdoc/Programas/fastqc_v0.11.9/fastqc`

Now whrn I try `fastqc -v` it says `-bash: /usr/bin/fastqc: No such file or directory`

**Comment by s-andrews** [comment]
There shouldn't be anything in ```/usr/bin/fastqc``` so something's wrong.

Can you show the output of:

1. ```which fastqc```
2. ```ls -l /usr/bin/fastqc```
3. ```ls -l /usr/local/bin/fastqc```

**Comment by MACRODER** [comment]
> 3\. ls -l /usr/local/bin/fastqc

Sure! Here it goes:
1. no output
2. ls: cannot access '/usr/bin/fastqc': No such file or directory
3. lrwxrwxrwx 1 root root 68 Mar 11 12:39 /usr/local/bin/fastqc -> mnt/c/Users/MacaRW/Documents/Postdoc/Programas/fastqc_v0.11.9/fastqc

**Comment by s-andrews** [comment]
So either /usr/local/bin isn't in your PATH (which is unlikely), or the location your symlink points to isn't there, or the fastqc launch script doesn't have execute permissions.  Let's check.  Can you run:

1. ```echo $PATH```

2. ```ls -l mnt/c/Users/MacaRW/Documents/Postdoc/Programas/fastqc_v0.11.9/fastqc```

3. ```ls -l /mnt/c/Users/MacaRW/Documents/Postdoc/Programas/fastqc_v0.11.9/fastqc```

**Comment by MACRODER** [comment]
1. long list of paths, among them /usr/local/bin
2. ls: cannot access 'mnt/c/Users/MacaRW/Documents/Postdoc/Programas/fastqc_v0.11.9/fastqc': No such file or directory
3. -rwxrwxrwx 1 macarw macarw 14998 Jan  8 14:04 /mnt/c/Users/MacaRW/Documents/Postdoc/Programas/fastqc_v0.11.9/fastqc

**Comment by s-andrews** [comment]
Thanks.  That means your symlink is broken because it's missing the leading / at the start of the path.

You should be able to fix it by running:

```sudo rm /usr/local/bin/fastqc```

```sudo ln -s /mnt/c/Users/MacaRW/Documents/Postdoc/Programas/fastqc_v0.11.9/fastqc /usr/local/bin/fastqc```

**Comment by MACRODER** [comment]
And that was the problem!! It works now. Thank you SO MUCH for taking the time and help me find the solution :) :) :)

**Comment by s-andrews** [comment]
No problem. Glad to hear it's working now.

**Comment by Jospin-Dk** [comment]
Hello,
I have been trying to download fastqc on mac and i've been facing some problems if someone could please help
1- I have downloaded the zip file from: https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.7.zip
2- I opened the file and ran the command: chmod +x fastqc
3- I ran: sudo ln -s /Absolute/path/to/fastqc /usr/local/bin/fastqc
then if I run: which fastqc I get no message from the terminal
and if I run: fastqc --help I get "-bash: fastqc: command not found"

any idea on what could be the problem ?

**Comment by s-andrews** [comment]
The part which says ```/Absolute/path/to/fastqc``` isn't meant to be taken literally.  It should be replaced with the path to wherever you actually put the program.  For instance if you put FastQC into your Applications folder then it would be;

```sudo ln -s /Applications/FastQC/fastqc /usr/local/bin/fastqc```

Likewise, the chmod command needs to be run when you are in the folder with the fastqc launch script, so you'd need to do something like:

```cd /Applications/FastQC```

...before doing this chmod.

**Comment by Jospin-Dk** [comment]
yes, I just wrote /Absolute/path/to/fastqc in order not to write my real absolute path and yes I did navigate to the FastQC folder before running the chmod command. 
After running the sudo command I navigated to /usr/local/bin and after using ls I found that fastqc was there. that means that the link was established right ? 
however still when I write: which fastqc, I get no message from the terminal and also when I write fastqc --help I get: "-bash: fastqc: command not found". 
if I navigate to FastQC and write: ./fastqc and I specify a fastq file the script runs normally.

**Comment by s-andrews** [comment]
OK, so if the ```./fastqc``` works then the permissions on the file must be OK, so it must either be the link being broken, or your PATH is messed up.  Let's check.  Can you show the output of:

```ls -l /usr/local/bin/fastqc```

```echo $PATH```

**Comment by Jospin-Dk** [comment]
~: ls -l /usr/local/bin/fastqc
lrwxr-xr-x  1 root  admin  41 Mar 17 17:53 /usr/local/bin/fastqc -> /Users/jospindeek/Desktop/capstone/FastQC
~: echo $PATH
/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

**Comment by s-andrews** [comment]
OK thanks.  Your link is pointing to the FastQC install folder and not to the actual launch script.

If you do:

```sudo rm /usr/local/bin/fastqc```

followed by

```ln -s /Users/jospindeek/Desktop/capstone/FastQC/fastqc /usr/local/bin/fastqc```

then it should start working.

**Comment by Jospin-Dk** [comment]
thank you so much for the help!

**Comment by marionamujal** [comment]
Hello there,
I have been trying to install fastqc but when I type ./fastqc, I get the error below. Requesting for your help. Thanks
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at javax.swing.JFrame.<init>(JFrame.java:189)
        at uk.ac.babraham.FastQC.FastQCApplication.<init>(FastQCApplication.java:63)
        at uk.ac.babraham.FastQC.FastQCApplication.main(FastQCApplication.java:338)

**Comment by s-andrews** [comment]
This is because you're running fastqc in a mode where it's going to try to launch its graphical interface, but you're operating in an environment which has no way to draw graphics.  You can fix this by either

1. Running fastqc in non-interactive mode so that it calculates its reports without trying to draw a user interface.

2. Setting up your environment to allow graphics to be drawn.

To do the first just supply the name of the file(s) that you want to analyse on the command line, so instead of running;

```./fastqc```

You'd run:

```./fastqc mydata1.fq.gz mydata2.f2.gz etc.```

..and fastqc will create the HTML reports for the files you supplied non-interactively.  You'll still need to work out how you're going to look at the reports (eg copying them back to your local machine), but fastqc will have done its bit.

For the second option you'll need to run an X server on your local machine, and then when you connect to your linux box and add an option to create an X-tunnel when you set up your SSH connection.  Exactly how you do this will depend on the operating system and software you're using on your desktop.  The normal combination of software we use would be:

OSX: XQuartz (www.xquartz.org)

Windows: VcSrv (https://sourceforge.net/projects/vcxsrv/) and Putty (https://www.chiark.greenend.org.uk/~sgtatham/putty/)

There are plenty of tutorials showing how to use these but if you can't figure it out write back here and I'll go through it.

**Comment by marionamujal** [comment]
Thank you for this;
About running an  X server on my local machine?
Was trying to use Xming and putty but was not successful. echo $DISPLAY
still returns nothing.
My Linux distribution is CentOS Linux

**Comment by s-andrews** [comment]
In your putty options did you set Connection > SSH > X11 > Enable X11 forwarding?

On your linux machine do you get something back if you run:

```which xauth```

**Comment by marionamujal** [comment]
which xauth  gives me this  /usr/bin/xauth
Yes i set this "Connection > SSH > X11 > Enable X11 forwarding" in my putty

**Comment by s-andrews** [comment]
Well that's super weird then - that should be enough to at least get you a $DISPLAY variable set in your shell.

Do you see a file called .Xauthority in your home directory? (you'll need to use ```ls -a``` to see it as it's a hidden file.  If you do can you try deleting it and then logging out and in again.

Do you get any warning or error messages when you log in?

**Comment by marionamujal** [comment]
So echo $DISPLAY now shows localhost:10.0
I don't have  .Xauthority in my home directory I checked using ls -la

Do you get any warning or error messages when you log in? No, I don't get
any errors once I log in.

**Comment by marionamujal** [comment]
What could have gone wrong?
xclock and xeyes now work fine.
which fastqc gives  /usr/local/bin/fastqc
fastqc --version just hangs, does not run
I tried running fastqc still non-interactively and it still doesn't run,
doesn't give any error.

Thank you

**Comment by Jospin-Dk** [comment]
Hello,
I was able to download the fastqc and it works fine.
However, I want to ask about automating the tool and implementing it in a pipeline.
What I would like to do is  run fastqc on a set of files then look at the per base sequence quality score and mark the bases that score below a threshold (let's say 20) and then have another tool (trimmomatic) remove those bases before I proceed with my analysis.
Is there any command that could help me do this or should I write my own script to make it work ?

Thank you for your time

**Comment by sarabarzinje** [comment]
Hello, Im trying to download this and run it in my terminal, but I just get command not found...

**Comment by magobu** [comment]
I tried to install FastQC in my MacBook pro Catalina and when I click on the icon to open it I get this message:
“FastQC” cannot be opened because the developer cannot be verified"

To download it, I cliked on: [FastQC v0.11.9 (Mac DMG image)](https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.9.dmg)
from the babraham webpage:[babraham
](https://www.bioinformatics.babraham.ac.uk/projects/download.html#fastqc)

**Comment by s-andrews** [comment]
From the https://raw.githubusercontent.com/s-andrews/FastQC/master/INSTALL.txt:

FastQC is not a signed application therefore it may initially be blocked by the
Gatekeeper application.  To avoid this open FastQC by right clicking on the app
and selecting open.  This may prompt you to allow it to open.  If it is still
blocked go to System Preferences > Security and Privacy and you should see an option
to allow the application to open.  You only need to do this once and the preference
should be remembered by OSX.

Hope this gets you up and running.

**Comment by gent-luke** [comment]
> 1. which fastqc
> 2. ls -l /usr/bin/fastqc
> 3. ls -l /usr/local/bin/fastqc

Hi! I've got the GUI version but also I am keen on using the command line as I'm needing to use Bismark and such also. 

So I've selected this part here to reply to as I wasn't sure where I could ask for help on here if that is okay, please let me know if I've done something incorrect. 

Here are my answers for when I type these in:

1. fastqc not found
2. ls: /usr/bin/fastqc: No such file or directory
3. lrwxr-xr-x  1 root  admin  22  3 Apr 11:26 /usr/local/bin/fastqc -> /path/to/FastQC/fastqc

I'm not sure where to go from here to make sure to see if it is working correctly. I'm already having issues locating and executing Bismark from my terminal so I'm certainly a novice, which I do apologise for the annoyances I create.

**Comment by gent-luke** [comment]
> 3\. lrwxr-xr-x  1 root  admin

Also this is what I get when I run echo $PATH:
echo $PATH
/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

**Comment by s-andrews** [comment]
Hi @gent-luke 

In the instructions we gave for installing the command line version the bit which says ```/path/to/FastQC/fastqc``` isn't meant to be taken literally, but replaced by the actual location of fastqc on your system, so if you had installed it in your home directory the command to put it into /usr/local/bin wouldn't be:

```sudo ln -s /path/to/FastQC/fastqc /usr/local/bin/fastqc```

..but rather something like:

```sudo ln -s /home/lukegent/FastQC/fastqc /usr/local/bin/fastqc```

..you'd need to use the actual folder you'd unzipped everything in to, and we don't know what that would be.  If you can figure that out, then delete the existing symlink in /usr/local/bin then recreate it with the correct location then hopefully that will get you one step closer.  If you're still having problems then give me the updated values from those commands and the full path where fastqc is installed and we'll do some more step by step instructions.

**Comment by gent-luke** [comment]
> /usr/local/bin/fastqc

Hi! Apologies didn't get the notification for your reply, will have to check my settings.

What you said makes absolute sense that it shouldn't be taken literally! So I located the folder I unzipped everything into which I acutely named FASTQC_ZipLoc and adjusted what you said into:

sudo ln -s /Users/lukeg/OneDrive\ -\ UCLan/miSeq/FASTQC_ZipLoc/FastQC/fastqc /usr/local/bin/fastqc

It returned: 
ln: /usr/local/bin/fastqc: File exists

So I presume I should do:
sudo rm /usr/local/bin/fastqc
followed by:
sudo ln -s /Users/lukeg/OneDrive\ -\ UCLan/miSeq/FASTQC_ZipLoc/FastQC/fastqc /usr/local/bin/fastqc

Will that delete the existing symlink and recreate with the correct location? 

P.S. Apologies for the way one of my subfolders looks like 'OneDrive\ -\ UCLan' is how it is formatted when I go through the directories using 'cd', not sure if that is contributing any issues.

**Comment by s-andrews** [comment]
Yes, deleting the existing symlink then creating the new one should get you up and running.

The weird quoting of the OneDrive folder is fine, that's what you need to do if you have spaces in file/folder names (or you can just put the whole path in quotes, which also works).

**Comment by gent-luke** [comment]
Okay so I've done that now and when I redo the questions I outlined above I get:

1. fastqc not found
2. ls: /usr/bin/fastqc: No such file or directory
3. lrwxr-xr-x  1 root  admin  63  4 Apr 10:19 /usr/local/bin/fastqc -> /Users/lukeg/OneDrive - UCLan/miSeq/FASTQC_ZipLoc/FastQC/fastqc

I'm so whilst 3 may look correct now (I believe based on what you've said), my concern is that 'which fastqc' still doesn't locate it, apologies for the step-by-step guidance

Thank you for the tip regarding if a folder has spaces!

**Comment by tmancill** [comment]
Hi @gent-luke, based on what you've shared, it appears that the binary is installed in `/usr/local/bin` and not in `/usr/bin`.  The `which` command only searches the directories in the `PATH`, so the solution may be as simple as adding `/usr/local/bin` to your `PATH`.  The exact instructions may depend on your shell, but you can try running this command to make /usr/local/bin the first element in the PATH:

`export PATH=/usr/local/bin:$PATH`

If this works for you, there is a write-up on permanently updating your PATH [here](https://gist.github.com/nex3/c395b2f8fd4b02068be37c961301caa7).
